function m(b,a,c,d){b.s.ob(b.tb,a,c,d)}function n(b,a,c,d){b.s.da?m(b,a,c,d):b.s.Oe()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.s.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Wb||(b.s.zc(b.de),b.Wb=!0)}window.La=class{constructor(b,a){this.s=b;this.tb=a;this.Wb=!1;this.de=()=>this.Qa()}kd(){}Qa(){}};
window.Bf=class{constructor(){this.fd=-1}j(){-1!==this.fd&&(self.clearTimeout(this.fd),this.fd=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Va.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ub}
window.od=class extends self.La{constructor(b,a){super(b,a);this.Va=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Va.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Va.get(c.elementId),e=d.Ub;d.Nd?e.style.display=c.isVisible?"":"none":d.gf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Va.get(c.elementId),e=d.Ub,f=this.s;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.mf=g;g=f.qd(g);g!==d.Ea&&(e.remove(),f.sc(g).appendChild(e),d.Ea=g,f.Ic());c=c.htmlZIndex;c!==d.Qc&&(d.Qc=c,f.Ic());d.Nd||(d.Nd=!0,d.gf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.rf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.vf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);let la=!1;
window.Pa=class b{constructor(a){this.da=a.xf;this.wa=null;this.aa="";this.cb=a.uf;this.Jb={};this.Xa=this.ta=null;this.Ua=[];this.ma=null;this.Rd=!0;this.M=[];this.$c=[];this.ad=!1;this.ee=()=>this.Me();this.Sc=!1;this.Kd=0;this.yb=null;this.bb=-1;this.lf=()=>this.Xe();this.Gb=new Set;this.gd=null;this.fe=[];this.A=a.ge;this.Xb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.Na()?self.chrome.webview.addEventListener("message",c=>this.zd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.zd(c));this.$b=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.af(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Se());this.B("runtime","cordova-fetch-local-file",c=>this.Te(c));this.B("runtime","create-job-worker",()=>this.Ue());this.B("runtime","send-wrapper-extension-message",c=>this.$e(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Ob(a)):this.Ob(a)}j(){this.Ac();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Xa&&(this.Xa.j(),this.Xa=null);for(const {canvas:a,
gb:c}of this.M)a.remove(),c.remove();this.M.length=0}ye(){return this.M[0].canvas}qd(a){return Math.min(a,this.M.length-1)}sc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].gb}Ce(){return ba&&"cordova"===this.A}mb(){const a=navigator.userAgent;return ba&&ka.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ae(){return y}rd(){return y&&ka.has(this.A)}td(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Na(){return this.td()||"xbox-uwp-webview2"===this.A}async Ob(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.A?this.pb({type:"ready"}):this.Na()&&(this.cf(),this.fe=(await this.Re()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.$b={};await this.Je();for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.$b.hasOwnProperty(c)?a.fb[d]={rf:!0,vf:this.$b[c]}:this.qa.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.qa[c]))}a.oc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.zc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.tf?this.aa=a.tf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.zf&&(this.Jb=a.zf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.We(d));this.yb=
new self.De(this);await oa(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Qe(a,c.port2):await this.Pe(a,c.port2)}Cc(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?this.Jb["workermain.js"]:"playable-ad"===
this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Xb)return a=await this.Kb(d.qf?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}xd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.lb(),k=a.Ef,l=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ge;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Df,jobScheduler:{inputPort:A.Rc,outputPort:A.Zc,maxNumWorkers:A.hf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cb+"opus.wasm.wasm",isFileProtocol:this.Xb,isiOSCordova:this.Ce(),isiOSWebView:this.mb(),isWindowsWebView2:this.td(),isAnyWebView2Wrapper:this.Na(),wrapperComponentIds:this.fe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Qe(a,c){const d=this.Cc(a.yf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.qc(d,this.aa,{type:"module",name:"Runtime",qf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,gb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.oc||[],k=a.fb;h=await Promise.all(h.map(l=>this.Ra(l)));k=await Promise.all(k.map(l=>this.Ra(l)));if("cordova"===this.A)for(let l=0,p=a.nc.length;l<p;++l){const r=
a.nc[l],t=r[0];if(t===a.hd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ra(t)}this.ta.postMessage(Object.assign(this.xd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.nc,mainProjectScript:a.hd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...pa(this.yb)]);this.Ua=F.map(l=>new l(this));this.wd();qa(e);ra(g);sa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.s.ud(r.tb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.ob("runtime","go-to-last-error-script"))}async Pe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,gb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ua=F.map(h=>new h(this));this.wd();qa(d);ra(e);e=a.fb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.oc)){var f=[...a.oc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ra(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.hd;const g=a.nc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ra(k),await z(k),"preview"!==this.A||e[h]||this.Bd(h,"main script did not run to completion")}catch(l){this.Bd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ra(k),await z(k);"preview"===this.A&&"object"!==typeof self.Af.Cf?(this.Qb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.xd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ja}),sa(this.ma),this.yd(),this.Xa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Xa,
a))}Bd(a,c){this.Qb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Qb()}Qb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ue(){const a=await ta(this.yb);return{outputPort:a,transferables:[a]}}af(a){if(!this.Sc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,gb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Rd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Rd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,gb:p}=this.M.pop();p.remove();this.da&&!d?this.$c.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,qa(c),ra(d),this.M.push({canvas:c,gb:d});for(const l of this.Ua)if(l instanceof window.od&&l.rb)for(const p of l.Va.values())e=l.s.qd(p.mf),f=p.Ea,-1!==e&&-1!==f&&e!==f&&(f=p.Ub,f.remove(),l.s.sc(e).appendChild(f),p.Ea=e);this.Ic();return{addedCanvases:a,transferables:k}}Se(){for(const a of this.$c)a.remove();this.$c.length=0}Ic(){this.ad||(this.ad=!0,this.zc(this.ee))}Me(){this.Ad(this.ee);
this.ad=!1;let a=[];for(var c of this.Ua)if(c instanceof window.od){var d=c.rb?[...c.Va.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ea,l=h.Ea;return k!==l?k-l:g.Qc-h.Qc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ea!==c&&(this.vd(c,a.slice(d,e)),c=g.Ea,d=e)}d<e&&this.vd(c,a.slice(d,e))}vd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Ub);var d=new Set(c);a=this.sc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Oe(){if(this.da)throw Error("not available in worker mode");return this.Xa}ob(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ud(a,c,d,e,f){const g=ia++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ve(a);if("result"===c)this.Ye(a);else if("runtime-ready"===c)this.Ze();else if("alert-error"===c)this.Qb(),alert(a.message);else if("creating-runtime"===c)this.yd();else throw Error(`unknown message '${c}'`);}Ve(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Pb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Pb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Pb(f,!1,""+h)}):this.Pb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Pb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ye(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static hb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}wd(){for(const a of this.Ua)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}We(a){this.ob("debugger","message",a)}Ze(){for(const a of this.Ua)a.kd()}static lb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||la)}static Cd(a){la=!!a}zc(a){this.Gb.add(a);
this.Hc()}Ad(a){this.Gb.delete(a);0===this.Gb.size&&this.Ac()}Hc(){-1===this.bb&&0<this.Gb.size&&(this.bb=requestAnimationFrame(this.lf))}Ac(){-1!==this.bb&&(cancelAnimationFrame(this.bb),this.bb=-1)}Xe(){this.bb=-1;for(const a of this.Gb)a();this.Hc()}Ca(a){this.ma.Ca(a)}Oa(a){this.ma.Oa(a)}Gc(){this.ma.Gc()}Nb(a){this.ma.Nb(a)}Be(){return!!ea["audio/webm; codecs=opus"]}async df(a){a=await this.ud("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Fe(a){this.Sc=!0;this.Kd=
a}ze(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}sd(a){return!this.ze(a)}async Ra(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Xb&&this.sd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Te(a){const c=a.filename;switch(a.as){case "text":return await this.xe(c);case "buffer":return await this.Kb(c);default:throw Error("unsupported type");
}}nd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async xe(a){a=await this.nd(a);return await fa(a)}Bc(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Ke(a.filename,a.wf,a.pf)}}Kb(a){return new Promise((c,d)=>{D.push({filename:a,wf:e=>{E--;this.Bc();c(e)},pf:e=>{E--;this.Bc();d(e)}});this.Bc()})}async Ke(a,c,d){try{const e=await this.nd(a),f=await ha(e);c(f)}catch(e){d(e)}}zd(a){if("entered-fullscreen"===
a)b.Cd(!0),I(this.ma);else if("exited-fullscreen"===a)b.Cd(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.gd(a),this.gd=null):"extension-message"===c?this.ob("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}$e(a){this.pb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}pb(a){this.Na()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}cf(){window.moveTo=(a,c)=>{this.pb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.pb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Re(){return this.Na()?new Promise(a=>{this.gd=a;this.pb({type:"wrapper-init"})}):Promise.resolve()}async Je(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.Ie(c,d));
await Promise.all(a)}async Ie(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.$b[a]=c.str;else{let d=await this.Ne(c);d||(d=this.Le(c));this.qa[a]=d}}async Ne(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Le(a){a=this.bf(a);return this.He(a.data,
a.sf)}bf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{sf:a,data:d}}He(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.Pa,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},wa={dispatchRuntimeEvent:!0};function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);function qa(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function ra(b){b.addEventListener("selectstart",Ea);b.addEventListener("gesturehold",Ea);b.addEventListener("touchstart",Ea)}function sa(b){b.Jd=!0;b.Vc=b.s.oa();b.zb=b.s.ga()}
function I(b){if(!b.ka){var a=J.lb();a&&"any"!==b.dd&&Ha(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.Id=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.dc=!("hidden"!==document.visibilityState&&!Ga);return{isSuspended:b.dc}}
function Qa(b){b.Ed||(b.Ed=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ra(b){b.Dd||(b.Dd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Sa(b){await xa(b.url)}
function Ta(b,a){b.Ld=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ld)},250))}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.lb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Oa(b,a){b.dc!==a&&((b.dc=a)?b.s.Ac():b.s.Hc(),m(b,"visibilitychange",{hidden:a}),!a&&b.s.mb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Va(b,a,c){"Backspace"===c.key&&M(c);if(b.s.Na()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ua.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Xc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Xc=c.buttons)}}function Wa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Xa(b,a,c,d){const e=b.oa(),f=b.ga();b.eb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb()}):10>d&&Ya(b,e,f,d+1)}function Ya(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>Xa(b,a,c,d),48)}
function Ha(b){b=b.dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.hb(class extends self.La{constructor(b){super(b,"runtime");this.Jd=!1;this.eb=-1;this.dd="any";this.dc=this.Dd=this.Ed=!1;this.kc=document.createElement("div");this.kc.className="c3-screen-reader-text";this.kc.setAttribute("aria-live","polite");document.body.appendChild(this.kc);this.Ga=null;this.ka=!1;this.Ld="";this.Mc=-1;this.Id=!1;this.Vc=b.oa();this.zb=b.ga();this.za=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ia(c));b.B("runtime","raster-svg-image",c=>Ja(c));b.B("runtime","get-svg-image-size",c=>Ka(c));b.B("runtime","set-target-orientation",c=>{this.dd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ma(c));b.B("runtime","go-to-script",c=>Ma(c));b.B("runtime","before-start-ticking",()=>Na(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Qa(this));b.B("runtime","enable-device-motion",()=>Ra(this));b.B("runtime","add-stylesheet",c=>Sa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.kc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.s.ye().style.display="";this.s.Fe(c.duration)});b.B("runtime","export-to-video-progress",c=>Ta(this,c));b.B("runtime","exported-to-video",c=>{window.nf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.nf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ba(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Xc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Jd){var c=this.oa();var d=this.ga();if(this.s.rd()){if(this.Id){if(this.Vc===
c&&d<this.zb){this.Ib=this.zb-d;Wa(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Wa(this,d,this.Ib))}this.Vc=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb()});this.s.mb()&&(-1!==this.eb&&clearTimeout(this.eb),Xa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Ua(this,c));window.addEventListener("webkitfullscreenerror",c=>Ua(this,c));window.addEventListener("mozfullscreenerror",c=>Ua(this,c));if(b.mb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ba(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Ya=new Set;this.bc=new WeakSet;this.va=!1}kd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,wa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},wa);this.Xc=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||Ba(a))&&m(this,"keyboard-blur",null,wa)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,va));window.addEventListener("mousemove",a=>N(this,"mousemove",a,va));window.addEventListener("mouseup",a=>N(this,"mouseup",a,va));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Za(a.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.s.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Gc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.s.Ae()&&!this.s.rd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Wa(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.s.mb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.s.oa()}ga(){return this.s.ga()}Gc(){var b=[...this.Ya];this.Ya.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.bc.has(a)||this.Ya.add(a)})}Ca(b){if("function"!==
typeof b.play)throw Error("missing play function");this.bc.delete(b);let a;try{a=b.play()}catch(c){this.Ya.add(b);return}a&&a.catch(()=>{this.bc.has(b)||this.Ya.add(b)})}Oa(b){this.Ya.delete(b);this.bc.add(b)}Nb(b){this.va=!!b}});"use strict";
async function oa(b){if(b.ef)throw Error("already initialised");b.ef=!0;var a=b.xa.Cc(("playable-ad"===b.xa.A?b.xa.cb:"")+"dispatchworker.js");b.Lc=await b.xa.qc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Zc=await ta(b)}function pa(b){return[b.Rc,b.Zc]}
async function ta(b){const a=b.Sd.length;var c=b.xa.Cc(("playable-ad"===b.xa.A?b.xa.cb:"")+"jobworker.js");c=await b.xa.qc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Lc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Sd.push(c);return e.port1}
self.De=class{constructor(b){this.xa=b;this.sb=b.aa;this.sb="preview"===b.A?this.sb+"workers/":this.sb+b.cb;this.hf=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Sd=[];this.Zc=this.Rc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Pa({xf:!1,yf:"workermain.js",fb:["scripts/c3runtime.js"],nc:[],hd:"",uf:"scripts/",oc:[],ge:"html5"}));"use strict";const $a=180/Math.PI;
async function ab(b,a){if(a.isiOSCordova||a.isSafari)b.fc=!0;b.ed=a.timeScaleMode;b.Xd=["equalpower","HRTF","soundfield"][a.panningModel];b.Hd=["linear","inverse","exponential"][a.distanceModel];b.Yd=a.refDistance;b.Wd=a.maxDistance;b.$d=a.rolloffFactor;if(b.s.Sc)b.fc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Kd)});else{var c={latencyHint:a.latencyHint};b.ce||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");bb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&bb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function cb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Td=g.slice(0);db(b,g);try{b.R=await eb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.xb){fb(u,p.x,p.y,p.z,p.angle);var C=self.ib.Ge;u.ra[0]!==C(A)&&
(u.ra[0]=C(A),u.F.coneInnerAngle=C(A));u.ra[1]!==C(ma)&&(u.ra[1]=C(ma),u.F.coneOuterAngle=C(ma));u.ra[2]!==na&&(u.ra[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),gb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(ub){console.error("[Construct] Audio: error starting playback: ",ub);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.jd--;0===d.jd&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function hb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await jb(b,c);for(const h of S(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Wa=g;h.be=a}T(b)}async function kb(b,a){const c=a.tags;a=a.rate;await jb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function lb(b,a){const c=a.tags;a=a.pos;await jb(b,c);for(const d of S(b,c))d.wc(a)}
async function mb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await eb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function nb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function ob(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.me(b,...e);else if("delay"===c)d=new self.ke(b,...e);else if("convolution"===c){var g=d=new self.je(b,f.ha,...e),h=a.bufferType;g.Fd=a.bufferOriginalUrl;g.Gd=h}else if("flanger"===c)d=
new self.ne(b,...e);else if("phaser"===c)d=new self.pe(b,...e);else if("gain"===c)d=new self.oe(b,...e);else if("stereopan"===c)d=new self.re(b,...e);else if("tremolo"===c)d=new self.se(b,...e);else if("ringmod"===c)d=new self.qe(b,...e);else if("distortion"===c)d=new self.le(b,...e);else if("compressor"===c)d=new self.ie(b,...e);else if("analyser"===c)d=new self.he(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Qd=l.length;d.cd=
h;l.push(d);pb(g,h)}qb(b)}
async function rb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.lc=a.timeScale;b.Nc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.va=a.isSilent;b.s.Nb(b.va);b.ac=a.masterVolume;b.Ta.gain.value=
b.ac;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>ob(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>sb(b,f,c)));T(b)}
async function tb(b,a){try{const c=b.g.suspend(a.time);b.Pd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.ob("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>vb(d)),b.Pd=!0);await c}catch(c){vb(c)}}
function bb(b){b.Vb||(b.Pc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Vb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.kb()===c)return await wb(g),g;if(f)return null;if(e&&(b.fc||b.Od)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ce;e&&f&&(b.Od=!0);c=!e||b.fc||f?new self.ve(b,a,c,d,e,f):new self.te(b,a,c,d,e);b.ia.push(c);await wb(c);b.Vd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Vd.add(a));return c}
function xb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function yb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function pb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of zb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Wc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*zb(b,a){if(a)for(const c of b.H)xb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ab(b,a,c){return c?b.s.df(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Bb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(xb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function eb(b,a,c,d,e,f){for(const g of b.H)if(g.kb()===c&&(g.pc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Jc?new self.ue(a.u,a,e):new self.we(a.u,a,e);b.H.push(e);return e}
function db(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={jd:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.jd++}function jb(b,a){return(b=b.Fb.get((0===a.length?b.Td:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Sa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Cb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function qb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Db(b)))}
function Db(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.jb());m(b,"fxstate",{fxstate:a});b.Tc=!1}
async function sb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await eb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],f=d.orient,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],e.setPosition(...b.$a),e.setOrientation(...b.Za),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),gb(b,d));c.Play(k,l,p,0);a.isPlaying||c.nb();c.Ec(a)}}}function vb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.La{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Vb=this.Pc=!1;this.ya=()=>{if(!this.Pc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Vb&&(this.Pc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Vb=!1)}};this.ia=[];this.H=[];this.R=null;this.Td=[];this.Vd=new Set;this.Ud=-1;this.Fb=new Map;this.ac=1;this.va=!1;this.ed=0;this.lc=1;this.Nc=0;this.Xd="HRTF";this.Hd="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Od=this.fc=!1;this.ce=this.s.Be();this.ja=new Map;this.Sa=new Set;this.Pd=this.Tc=!1;this.Wc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Wc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(yb(this,this.Wc))};this.Tb=null;self.C3Audio_GetOutputStream=()=>{this.Tb||(this.Tb=this.g.createMediaStreamDestination(),this.Ta.connect(this.Tb));return this.Tb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>ab(this,a)],["play",a=>cb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.nb():d.Mb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>hb(this,a)],["set-master-volume",a=>{this.ac=a.vol;this.Ta.gain.value=this.ac}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Eb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.s.Nb(this.va);for(const c of this.H)c.Rb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.xc(a)}],["set-playback-rate",a=>kb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),gb(d,a)}],["seek",a=>lb(this,a)],["preload",a=>mb(this,a)],["unload",a=>nb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.yc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ob(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);qb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);pb(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Nc=a.gameTime;this.Ud=a.tickCount;if(0!==this.ed)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&fb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>rb(this,a)],["offline-render-audio",a=>tb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Lb(){return this.va}Ca(b){this.s.Ca(b)}Oa(b){this.s.Oa(b)}Qa(){for(var b of this.Sa)b.Qa();
b=this.g.currentTime;for(var a of this.H)a.Qa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.jb());m(this,"state",{tickCount:this.Ud,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.cd,index:c.Qd,peak:c.ab,rms:c.Zd,binCount:c.l.frequencyBinCount,freqBins:c.Md}))});0===a.length&&0===this.Sa.size&&this.Wb&&(this.s.Ad(this.de),this.Wb=!1)}static Ge(b){return b*$a}static pd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ee(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Pa.hb(self.ib);"use strict";function wb(b){b.Zb||(b.Zb=b.Dc());return b.Zb}self.ld=class{constructor(b,a,c,d,e){this.u=b;this.kf=a;this.Ja=c;this.T=d;this.ff=e;this.Jc="";this.Zb=null}j(){this.Zb=this.u=null}Dc(){}V(){return this.u.V()}tc(){return this.kf}kb(){return this.Ja}rc(){return this.T}Aa(){return this.ff}fa(){}};"use strict";
self.te=class extends self.ld{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Jc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}j(){Bb(this.u,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Dc(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Fb(b){if(b.Fa)return b.Fa;var a=b.u.s;if("cordova"===a.A&&a.sd(b.Ja)&&a.Xb)b.Fa=await a.Kb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Gb(b){if(b.ha)return b.ha;b.ha=await Ab(b.u,b.Fa,b.jf);b.Fa=null}
self.ve=class extends self.ld{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Jc="webaudio";this.ha=this.Fa=null;this.jf=!!f}j(){Bb(this.u,this);this.ha=this.Fa=null;super.j()}async Dc(){try{await Fb(this),await Gb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Hb=0;
function Q(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Xd,b.F.distanceModel=b.u.Hd,b.F.refDistance=b.u.Yd,b.F.maxDistance=b.u.Wd,b.F.rolloffFactor=b.u.$d),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Yb!==a&&(b.Yb=a,b.Yb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function gb(b,a){b.Yb&&b.bd!==a&&(b.ca.pan.value=a,b.bd=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Wa=-1;b.G.gain.value=b.uc()}function Eb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Rb())}
function fb(b,a,c,d,e){if(b.xb){var f=b.$a,g=b.Za,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Uc?b.u.Nc:performance.now()/1E3}
self.md=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Sb=Hb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.xb=!1;this.$a=[0,0,0];this.Za=[0,0,0];this.ra=[0,0,0];this.ca=null;this.Yb=!1;this.bd=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ka=1;this.ua=!1;this.la=1;b=this.u.ed;this.Uc=1===b&&!this.Aa()||2===b;this.Wa=this.pa=-1;this.be=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return yb(this.u,0<this.na.length?this.na[0]:"")}tc(){return this.P.tc()}kb(){return this.P.kb()}rc(){return this.P.rc()}Aa(){return this.P.Aa()}O(){}pc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ma(){}fa(){return this.P.fa()}Play(){}Ba(){}nb(){}Mb(){}Qa(b){-1!==this.Wa&&b>=this.Wa&&(this.Wa=-1,this.be&&this.Ba(),Cb(this.u,"fade-ended",this.na,this.Sb))}uc(){const b=this.Ka;return isFinite(b)?b:0}Lb(){return this.u.Lb()}Rb(){}xc(){}Da(){}wc(){}yc(){}vc(){}jb(){var b=
this.Sb,a=this.na,c=this.fa(),d=-1===this.Wa?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.$a,orient:this.Za,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.vc(),pan:f,stereoPan:this.ca?
this.bd:null}}Ec(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Eb(this,b.isMuted)}};"use strict";
self.ue=class extends self.md{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Fc()}j(){this.Ba();this.P.Eb.disconnect();super.j()}W(){return this.P.W()}Fc(){this.I=!0;this.pa=-1;Cb(this.u,"ended",this.na,this.Sb)}O(){return this.W().ended}pc(){return this.I?!0:this.O()}Ma(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.kb()}' to position '${c}': `,e)}this.u.Ca(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Oa(b);this.I=!0;this.J=!1;this.pa=-1}nb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Oa(b);this.J=!0}}Mb(){!this.J||this.I||this.O()||(this.u.Ca(this.W()),this.J=!1)}Rb(){this.W().muted=this.ua||this.Lb()}xc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Da(){let b=this.la;this.Uc&&(b*=this.u.lc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}wc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}vc(){return this.Ma()}yc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.W()),this.sa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.qb=null}
self.we=class extends self.md{constructor(b,a,c){super(b,a,c);this.o=null;this.cc=d=>this.Fc(d);this.Oc=!0;this.qb=null;this.S=this.ec=this.hc=0;this.Yc=1}j(){this.Ba();W(this);this.cc=null;super.j()}Fc(b){this.J||this.sa||b.target!==this.qb||(this.I=this.Oc=!0,this.pa=-1,W(this),Cb(this.u,"ended",this.na,this.Sb))}O(){return!this.I&&this.o&&this.o.loop||this.J?!1:this.Oc}pc(){return!this.o||this.I?!0:this.O()}Ma(){let b;b=this.J?this.S:this.ec+(V(this)-this.hc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Yc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ha;this.o.connect(this.G);this.qb=this.o;this.o.onended=this.cc;this.o.loop=b;this.o.start(d,c);this.J=this.I=this.Oc=!1;this.Y=b;this.la=1;this.hc=V(this);this.ec=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}nb(){this.J||this.I||this.O()||(this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.J=!0,this.o.stop(0))}Mb(){!this.J||this.I||this.O()||(W(this),
this.o=this.V().createBufferSource(),this.o.buffer=this.P.ha,this.o.connect(this.G),this.qb=this.o,this.o.onended=this.cc,this.o.loop=this.Y,U(this,this.Ka),this.Da(),this.o.start(0,this.S),this.hc=V(this),this.ec=this.S,this.J=!1)}uc(){return super.uc()*this.Yc}Rb(){this.Yc=this.ua||this.Lb()?0:1;U(this,this.Ka)}xc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Uc&&(b*=this.u.lc);this.o&&(this.o.playbackRate.value=b)}wc(b){this.I||this.O()||(this.J?this.S=b:(this.nb(),
this.S=b,this.Mb()))}vc(){return this.S}yc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ha,this.o.connect(this.G),this.qb=this.o,this.o.onended=this.cc,this.o.loop=this.Y,U(this,this.Ka),this.Da(),this.o.start(0,this.S),this.hc=V(this),this.ec=this.S,this.sa=!1)}Ec(b){super.Ec(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Qd=-1;this.T=this.cd="";this.m=null}j(){this.g=null}N(){}U(){}jb(){return{type:this.T,tag:this.cd,params:this.m}}}
self.me=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Cb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=X(this);this.vb.gain.value=c;this.v.connect(this.Cb);this.v.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ib.pd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.vb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Gd=this.Fd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.v.connect(this.ub);this.v.connect(this.h);this.ub.connect(this.i)}j(){this.v.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}jb(){const b=super.jb();b.bufferOriginalUrl=this.Fd;b.bufferUrl="";b.bufferType=this.Gd;return b}};
self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.oe=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ib.pd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.re=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Hb=X(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.v.connect(this.Hb);this.v.connect(this.h);this.Hb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.jc=X(this);this.ic=X(this);b=d;.01>b&&(b=.01);this.jc.gain.value=b;this.ic.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Kc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Kc[32768+e]=f,this.Kc[32768-
e-1]=-f;this.mc.curve=this.Kc;this.v.connect(this.jc);this.v.connect(this.h);this.jc.connect(this.mc);this.mc.connect(this.ic);this.ic.connect(this.i)}j(){this.v.disconnect();this.jc.disconnect();this.mc.disconnect();this.ic.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ie=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.he=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Md=new Float32Array(this.l.frequencyBinCount);this.ae=new Uint8Array(a);this.Zd=this.ab=0;b=this.u;b.Sa.add(this);T(b)}j(){this.u.Sa.delete(this);this.l.disconnect();super.j()}Qa(){this.l.getFloatFrequencyData(this.Md);this.l.getByteTimeDomainData(this.ae);const b=this.l.fftSize;let a=this.ab=0;for(var c=0;c<b;++c){let d=(this.ae[c]-
128)/128;0>d&&(d=-d);this.ab<d&&(this.ab=d);a+=d*d}c=self.ib.Ee;this.ab=c(this.ab);this.Zd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Ib(b,a){a=a.type;let c=!0;0===a?c=await Jb():1===a&&(c=await Kb());m(b,"permission-result",{type:a,result:c})}
async function Jb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Kb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Pa.hb(class extends self.La{constructor(b){super(b,"touch");q(this,"request-permission",a=>Ib(this,a))}});"use strict";
async function Lb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.Pa.hb(class extends self.La{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Ob()],["request-persistent",()=>Lb()]])}async Ob(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
function Mb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Nb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Ob(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Pb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Qb(){const b=await Rb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}
async function Sb(b){if(!b.Ia)try{b.Ia=await navigator.wakeLock.request("screen"),b.Ia.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ia=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Tb(b){const a=await Rb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Rb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Mb(b),Nb(b),Ob(b),Pb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.Pa.hb(class extends self.La{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>Qb()],["request-wake-lock",()=>Sb(this)],["release-wake-lock",()=>{this.Ia&&(this.Ia.release(),this.Ia=null)}]]);window.addEventListener("resize",()=>Tb(this));this.Ia=null}});
