const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.skymen_limit_fps,
		C3.Plugins.BinaryData,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Platform,
		C3.Behaviors.skymenTrail,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.skymen_limit_fps.Acts.SetMaxFPS,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetFramerateMinMax,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.ScriptsInEvents.Game_Event7,
		C3.Plugins.System.Cnds.ForEach,
		C3.ScriptsInEvents.Game_Event9,
		C3.ScriptsInEvents.Game_Event11,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.ScriptsInEvents.Game_Event14,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetY,
		C3.ScriptsInEvents.Game_Event34,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.ScriptsInEvents.Game_Event42,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.LOS.Exps.HitUID,
		C3.Behaviors.LOS.Exps.ReflectionX,
		C3.Behaviors.LOS.Exps.ReflectionY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareChildCount,
		C3.Plugins.System.Cnds.PickRandom,
		C3.ScriptsInEvents.Game_Event92,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.ScriptsInEvents.Game_Event95,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.ScriptsInEvents.Game_Event105,
		C3.ScriptsInEvents.Game_Event117,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.Game_Event126,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.ScriptsInEvents.Game_Event151_Act2,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.ScriptsInEvents.Game_Event159,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Bullet.Acts.StopStepping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Exps.IID,
		C3.ScriptsInEvents.Game_Event189,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SaveImage,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.ScriptsInEvents.E_js_events_Event5_Act2,
		C3.ScriptsInEvents.E_js_events_Event8_Act1,
		C3.ScriptsInEvents.E_js_events_Event9_Act1,
		C3.ScriptsInEvents.E_js_events_Event10_Act1,
		C3.ScriptsInEvents.E_js_events_Event18_Act1,
		C3.ScriptsInEvents.E_js_events_Event19_Act1,
		C3.ScriptsInEvents.E_js_events_Event20_Act1,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenOneProperty
	];
};
self.C3_JsPropNameTable = [
	{isPopupAds: 0},
	{Tween: 0},
	{BlackSquarePopupAds: 0},
	{TxtPopupAds: 0},
	{BlackSquarePopupAds2: 0},
	{BlackPopupAds: 0},
	{Sprite: 0},
	{checked: 0},
	{matched: 0},
	{in_cascade: 0},
	{to_start_match: 0},
	{fall: 0},
	{to_shot: 0},
	{angle_: 0},
	{next_ball: 0},
	{amazing: 0},
	{falling: 0},
	{Physics: 0},
	{Bullet: 0},
	{MoveTo: 0},
	{Solid: 0},
	{Flash: 0},
	{ball: 0},
	{Touch: 0},
	{aim_helper: 0},
	{Mouse: 0},
	{Browser: 0},
	{mouse_zone: 0},
	{ball_position: 0},
	{checker: 0},
	{DrawingCanvas: 0},
	{wall: 0},
	{current_ball: 0},
	{is_fire_ball: 0},
	{bullet_checker: 0},
	{top_checker: 0},
	{ball_position_group: 0},
	{position_: 0},
	{TiledBackground: 0},
	{ScrollTo: 0},
	{camera: 0},
	{LineOfSight: 0},
	{ball_spawmer: 0},
	{line2: 0},
	{invisible_wall: 0},
	{TiledBackground2: 0},
	{nomer: 0},
	{score: 0},
	{score_zone: 0},
	{score_anim: 0},
	{Anchor: 0},
	{t_score: 0},
	{TiledBackground3: 0},
	{checkj_fast_down_cascade: 0},
	{Sprite3: 0},
	{line3: 0},
	{Pin: 0},
	{ball_erase_line_helper: 0},
	{fon: 0},
	{poslejarilis: 0},
	{TiledBackground4: 0},
	{Sprite2: 0},
	{usti: 0},
	{treugolbik: 0},
	{Text: 0},
	{Text2: 0},
	{jolak: 0},
	{jolak2: 0},
	{treugolbik2: 0},
	{sankubik: 0},
	{jolak3: 0},
	{streakinfo: 0},
	{streaktxt: 0},
	{AMAZING: 0},
	{Sine: 0},
	{Fade: 0},
	{Sine2: 0},
	{"250score": 0},
	{"50score": 0},
	{"60score": 0},
	{"75score": 0},
	{"100score": 0},
	{"120score": 0},
	{"150score": 0},
	{"300score": 0},
	{"300score2": 0},
	{Audio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{TiledBackground5: 0},
	{BONUSSHOT: 0},
	{TiledBackground6: 0},
	{losebg: 0},
	{score_lose: 0},
	{restrat: 0},
	{t_highscore: 0},
	{LocalStorage: 0},
	{logogo: 0},
	{PlatformInfo: 0},
	{fff: 0},
	{jolak4: 0},
	{AGsitesidetableft: 0},
	{zvuljok: 0},
	{pause: 0},
	{Text3: 0},
	{TiledBackground7: 0},
	{resume: 0},
	{Instantgame_profile: 0},
	{invite: 0},
	{highscore_lose: 0},
	{invite2: 0},
	{banner_share: 0},
	{btn_revive: 0},
	{btn_bomb: 0},
	{bomb_zone: 0},
	{bomb_animation: 0},
	{T_REVIVE_TIMER: 0},
	{LimitFPS: 0},
	{ava: 0},
	{avaasti: 0},
	{playername: 0},
	{bombtext: 0},
	{Congratulations: 0},
	{Instantgame_profile2: 0},
	{ava2: 0},
	{Sprite6: 0},
	{primer: 0},
	{DrawingCanvas2: 0},
	{DrawingCanvas3: 0},
	{exampleshare: 0},
	{BinaryData: 0},
	{nothanks: 0},
	{onemorechanse: 0},
	{FireWork: 0},
	{invite3: 0},
	{switch_balls: 0},
	{Rotate: 0},
	{domalak: 0},
	{wunkir: 0},
	{light: 0},
	{Best_text: 0},
	{score_text: 0},
	{amazing2: 0},
	{rand_: 0},
	{Platform: 0},
	{Paper: 0},
	{greenscreen: 0},
	{share_game_Canvas: 0},
	{canyou: 0},
	{Congratulations2: 0},
	{highscore_banner: 0},
	{Instantgame_profile3: 0},
	{ava3: 0},
	{korona2: 0},
	{logogo2: 0},
	{screenshare: 0},
	{TrailRenderer: 0},
	{trail01: 0},
	{fire_particle: 0},
	{fire_particle2: 0},
	{tapinfo: 0},
	{hand: 0},
	{restart_jazuemes: 0},
	{TiledBackground8: 0},
	{resetprogress: 0},
	{yes: 0},
	{iks: 0},
	{reserprogresstext: 0},
	{buttons: 0},
	{info: 0},
	{PLAYING: 0},
	{LOSE: 0},
	{BALL_VEL: 0},
	{FALL_VEL: 0},
	{SCORE: 0},
	{streak: 0},
	{streak2: 0},
	{streak3: 0},
	{matchkosatin: 0},
	{colorball: 0},
	{touchX: 0},
	{touchY: 0},
	{highscore: 0},
	{reward: 0},
	{REVIVE_TIMER: 0},
	{CASCADE_NOT_MOVE: 0},
	{bomb: 0},
	{balldestroyaudio: 0},
	{combo: 0},
	{fast_down: 0},
	{angle_aim: 0},
	{x_: 0},
	{y_: 0},
	{to_shot_number: 0},
	{to_shot_number2: 0},
	{next_number: 0},
	{next_number2: 0},
	{next_id: 0},
	{shot__: 0},
	{moving: 0},
	{COLOR_FOR_CHECK: 0},
	{MATCHES2: 0},
	{next_color: 0},
	{distance_: 0},
	{is_wall: 0},
	{HAVE_MATCHES: 0},
	{CHECKS: 0},
	{asdf: 0},
	{fall_for_fireball: 0},
	{position_x: 0},
	{position_y: 0},
	{fall_for_fireball_: 0},
	{x1: 0},
	{x2: 0},
	{y1: 0},
	{y2: 0},
	{number: 0},
	{binary: 0},
	{js_Logs: 0},
	{js_Check: 0},
	{iOS: 0},
	{js_StartEvent: 0},
	{js_CompleteEvent: 0},
	{js_LoseEvent: 0},
	{js_RestartEvent: 0},
	{js_GameLoaded: 0},
	{timerAdsSeconds: 0},
	{js_ShowInterstitialEvent: 0},
	{js_ShowRewardedEvent: 0},
	{js_GiveRewardedEvent: 0},
	{name_event: 0},
	{param: 0},
	{type: 0},
	{js_win: 0},
	{js_lose: 0},
	{js_start: 0},
	{js_restart: 0},
	{js_n_level: 0},
	{a: 0},
	{enabledAudio: 0},
	{sec: 0},
	{isTimerAdsStated: 0},
	{isReadyToShowPopupAds: 0},
	{isReadyToShowAds: 0},
	{countTimerPopupAdsStarted: 0},
	{isPopupCloseActive: 0},
	{Score_game_PopUp: 0},
	{R_game: 0},
	{new_score: 0},
	{resetTimer: 0},
	{show_score: 0},
	{posX_Text: 0}
];

self.InstanceType = {
	BlackSquarePopupAds: class extends self.ISpriteInstance {},
	TxtPopupAds: class extends self.ITextInstance {},
	BlackSquarePopupAds2: class extends self.ISpriteInstance {},
	BlackPopupAds: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	aim_helper: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	mouse_zone: class extends self.ISpriteInstance {},
	ball_position: class extends self.ISpriteInstance {},
	checker: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	wall: class extends self.ISpriteInstance {},
	current_ball: class extends self.ISpriteInstance {},
	bullet_checker: class extends self.ISpriteInstance {},
	top_checker: class extends self.ISpriteInstance {},
	ball_position_group: class extends self.ISpriteInstance {},
	position_: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	camera: class extends self.ISpriteInstance {},
	ball_spawmer: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	invisible_wall: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	score_zone: class extends self.ISpriteInstance {},
	t_score: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	checkj_fast_down_cascade: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	line3: class extends self.ISpriteInstance {},
	ball_erase_line_helper: class extends self.ISpriteInstance {},
	fon: class extends self.ISpriteInstance {},
	poslejarilis: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	usti: class extends self.ISpriteInstance {},
	treugolbik: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	jolak: class extends self.ISpriteInstance {},
	jolak2: class extends self.ISpriteInstance {},
	treugolbik2: class extends self.ISpriteInstance {},
	sankubik: class extends self.ITextInstance {},
	jolak3: class extends self.ISpriteInstance {},
	streakinfo: class extends self.ITextInstance {},
	streaktxt: class extends self.ITextInstance {},
	AMAZING: class extends self.ISpriteInstance {},
	_250score: class extends self.ISpriteInstance {},
	_50score: class extends self.ISpriteInstance {},
	_60score: class extends self.ISpriteInstance {},
	_75score: class extends self.ISpriteInstance {},
	_100score: class extends self.ISpriteInstance {},
	_120score: class extends self.ISpriteInstance {},
	_150score: class extends self.ISpriteInstance {},
	_300score: class extends self.ISpriteInstance {},
	_300score2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	BONUSSHOT: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	losebg: class extends self.ITiledBackgroundInstance {},
	score_lose: class extends self.ITextInstance {},
	restrat: class extends self.ISpriteInstance {},
	t_highscore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	logogo: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	fff: class extends self.ISpriteInstance {},
	jolak4: class extends self.ISpriteInstance {},
	AGsitesidetableft: class extends self.ISpriteInstance {},
	zvuljok: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	resume: class extends self.ISpriteInstance {},
	Instantgame_profile: class extends self.ISpriteInstance {},
	invite: class extends self.ISpriteInstance {},
	highscore_lose: class extends self.ITextInstance {},
	invite2: class extends self.ISpriteInstance {},
	banner_share: class extends self.ISpriteInstance {},
	btn_revive: class extends self.ISpriteInstance {},
	btn_bomb: class extends self.ISpriteInstance {},
	bomb_zone: class extends self.ISpriteInstance {},
	bomb_animation: class extends self.ISpriteInstance {},
	T_REVIVE_TIMER: class extends self.ITextInstance {},
	LimitFPS: class extends self.IInstance {},
	ava: class extends self.ISpriteInstance {},
	avaasti: class extends self.ISpriteInstance {},
	playername: class extends self.ITextInstance {},
	bombtext: class extends self.ITextInstance {},
	Congratulations: class extends self.ISpriteInstance {},
	Instantgame_profile2: class extends self.ISpriteInstance {},
	ava2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	primer: class extends self.ITextInstance {},
	DrawingCanvas2: class extends self.IDrawingCanvasInstance {},
	DrawingCanvas3: class extends self.IDrawingCanvasInstance {},
	exampleshare: class extends self.ISpriteInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	nothanks: class extends self.ITextInstance {},
	onemorechanse: class extends self.ITextInstance {},
	FireWork: class extends self.IParticlesInstance {},
	invite3: class extends self.ISpriteInstance {},
	switch_balls: class extends self.ISpriteInstance {},
	domalak: class extends self.ISpriteInstance {},
	wunkir: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	Best_text: class extends self.ISpriteInstance {},
	score_text: class extends self.ISpriteInstance {},
	amazing2: class extends self.ISpriteInstance {},
	Paper: class extends self.ISpriteInstance {},
	greenscreen: class extends self.ISpriteInstance {},
	share_game_Canvas: class extends self.IDrawingCanvasInstance {},
	canyou: class extends self.ITextInstance {},
	Congratulations2: class extends self.ISpriteInstance {},
	highscore_banner: class extends self.ITextInstance {},
	Instantgame_profile3: class extends self.ISpriteInstance {},
	ava3: class extends self.ISpriteInstance {},
	korona2: class extends self.ISpriteInstance {},
	logogo2: class extends self.ISpriteInstance {},
	screenshare: class extends self.ISpriteInstance {},
	trail01: class extends self.ISpriteInstance {},
	fire_particle: class extends self.IParticlesInstance {},
	fire_particle2: class extends self.IParticlesInstance {},
	tapinfo: class extends self.ITextInstance {},
	hand: class extends self.ISpriteInstance {},
	restart_jazuemes: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	resetprogress: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	iks: class extends self.ISpriteInstance {},
	reserprogresstext: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {}
}